# Generated by Django 3.2.10 on 2022-07-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_item_txid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
