# Generated by Django 3.2.10 on 2022-07-28 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.CreateModel(
            name='ItemOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.owner')),
            ],
        ),
    ]
