# Generated by Django 3.2.10 on 2022-07-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220728_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='txId',
        ),
        migrations.AddField(
            model_name='itemowner',
            name='change_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemowner',
            name='txId',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
