# Generated by Django 3.2.10 on 2022-07-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220728_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='change_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='txId',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.DeleteModel(
            name='ItemOwner',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
