# Generated by Django 3.2.10 on 2022-08-08 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_item_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='nickname',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='OwnerTxId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
            ],
        ),
    ]
