# Generated by Django 3.2.10 on 2022-09-06 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220808_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeItem', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('change_date', models.DateTimeField(blank=True, null=True)),
                ('txId', models.CharField(blank=True, max_length=66, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='code',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='item',
            name='txId',
        ),
        migrations.DeleteModel(
            name='OwnerTxId',
        ),
        migrations.AddField(
            model_name='owner',
            name='nameItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
    ]
