# Generated by Django 3.2.10 on 2022-09-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220906_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='nameItem',
            new_name='item',
        ),
    ]
